/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoryRouteImport } from './routes/story'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessesIndexRouteImport } from './routes/businesses.index'
import { Route as BusinessesTechworksRouteImport } from './routes/businesses.techworks'
import { Route as BusinessesStructuresRouteImport } from './routes/businesses.structures'
import { Route as BusinessesEximRouteImport } from './routes/businesses.exim'
import { Route as BusinessesEnergiesRouteImport } from './routes/businesses.energies'
import { Route as BusinessesTechworksLoamyRouteImport } from './routes/businesses.techworks.loamy'
import { Route as BusinessesTechworksLoamyDashboardRouteImport } from './routes/businesses.techworks.loamy.dashboard'
import { Route as BusinessesTechworksLoamyAuthRouteImport } from './routes/businesses.techworks.loamy.auth'

const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesIndexRoute = BusinessesIndexRouteImport.update({
  id: '/businesses/',
  path: '/businesses/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesTechworksRoute = BusinessesTechworksRouteImport.update({
  id: '/businesses/techworks',
  path: '/businesses/techworks',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesStructuresRoute = BusinessesStructuresRouteImport.update({
  id: '/businesses/structures',
  path: '/businesses/structures',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesEximRoute = BusinessesEximRouteImport.update({
  id: '/businesses/exim',
  path: '/businesses/exim',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesEnergiesRoute = BusinessesEnergiesRouteImport.update({
  id: '/businesses/energies',
  path: '/businesses/energies',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesTechworksLoamyRoute =
  BusinessesTechworksLoamyRouteImport.update({
    id: '/loamy',
    path: '/loamy',
    getParentRoute: () => BusinessesTechworksRoute,
  } as any)
const BusinessesTechworksLoamyDashboardRoute =
  BusinessesTechworksLoamyDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => BusinessesTechworksLoamyRoute,
  } as any)
const BusinessesTechworksLoamyAuthRoute =
  BusinessesTechworksLoamyAuthRouteImport.update({
    id: '/auth',
    path: '/auth',
    getParentRoute: () => BusinessesTechworksLoamyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/businesses/energies': typeof BusinessesEnergiesRoute
  '/businesses/exim': typeof BusinessesEximRoute
  '/businesses/structures': typeof BusinessesStructuresRoute
  '/businesses/techworks': typeof BusinessesTechworksRouteWithChildren
  '/businesses/': typeof BusinessesIndexRoute
  '/businesses/techworks/loamy': typeof BusinessesTechworksLoamyRouteWithChildren
  '/businesses/techworks/loamy/auth': typeof BusinessesTechworksLoamyAuthRoute
  '/businesses/techworks/loamy/dashboard': typeof BusinessesTechworksLoamyDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/businesses/energies': typeof BusinessesEnergiesRoute
  '/businesses/exim': typeof BusinessesEximRoute
  '/businesses/structures': typeof BusinessesStructuresRoute
  '/businesses/techworks': typeof BusinessesTechworksRouteWithChildren
  '/businesses': typeof BusinessesIndexRoute
  '/businesses/techworks/loamy': typeof BusinessesTechworksLoamyRouteWithChildren
  '/businesses/techworks/loamy/auth': typeof BusinessesTechworksLoamyAuthRoute
  '/businesses/techworks/loamy/dashboard': typeof BusinessesTechworksLoamyDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/businesses/energies': typeof BusinessesEnergiesRoute
  '/businesses/exim': typeof BusinessesEximRoute
  '/businesses/structures': typeof BusinessesStructuresRoute
  '/businesses/techworks': typeof BusinessesTechworksRouteWithChildren
  '/businesses/': typeof BusinessesIndexRoute
  '/businesses/techworks/loamy': typeof BusinessesTechworksLoamyRouteWithChildren
  '/businesses/techworks/loamy/auth': typeof BusinessesTechworksLoamyAuthRoute
  '/businesses/techworks/loamy/dashboard': typeof BusinessesTechworksLoamyDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/sitemap.xml'
    | '/story'
    | '/businesses/energies'
    | '/businesses/exim'
    | '/businesses/structures'
    | '/businesses/techworks'
    | '/businesses/'
    | '/businesses/techworks/loamy'
    | '/businesses/techworks/loamy/auth'
    | '/businesses/techworks/loamy/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/sitemap.xml'
    | '/story'
    | '/businesses/energies'
    | '/businesses/exim'
    | '/businesses/structures'
    | '/businesses/techworks'
    | '/businesses'
    | '/businesses/techworks/loamy'
    | '/businesses/techworks/loamy/auth'
    | '/businesses/techworks/loamy/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/sitemap.xml'
    | '/story'
    | '/businesses/energies'
    | '/businesses/exim'
    | '/businesses/structures'
    | '/businesses/techworks'
    | '/businesses/'
    | '/businesses/techworks/loamy'
    | '/businesses/techworks/loamy/auth'
    | '/businesses/techworks/loamy/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoryRoute: typeof StoryRoute
  BusinessesEnergiesRoute: typeof BusinessesEnergiesRoute
  BusinessesEximRoute: typeof BusinessesEximRoute
  BusinessesStructuresRoute: typeof BusinessesStructuresRoute
  BusinessesTechworksRoute: typeof BusinessesTechworksRouteWithChildren
  BusinessesIndexRoute: typeof BusinessesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/': {
      id: '/businesses/'
      path: '/businesses'
      fullPath: '/businesses/'
      preLoaderRoute: typeof BusinessesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/techworks': {
      id: '/businesses/techworks'
      path: '/businesses/techworks'
      fullPath: '/businesses/techworks'
      preLoaderRoute: typeof BusinessesTechworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/structures': {
      id: '/businesses/structures'
      path: '/businesses/structures'
      fullPath: '/businesses/structures'
      preLoaderRoute: typeof BusinessesStructuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/exim': {
      id: '/businesses/exim'
      path: '/businesses/exim'
      fullPath: '/businesses/exim'
      preLoaderRoute: typeof BusinessesEximRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/energies': {
      id: '/businesses/energies'
      path: '/businesses/energies'
      fullPath: '/businesses/energies'
      preLoaderRoute: typeof BusinessesEnergiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/techworks/loamy': {
      id: '/businesses/techworks/loamy'
      path: '/loamy'
      fullPath: '/businesses/techworks/loamy'
      preLoaderRoute: typeof BusinessesTechworksLoamyRouteImport
      parentRoute: typeof BusinessesTechworksRoute
    }
    '/businesses/techworks/loamy/dashboard': {
      id: '/businesses/techworks/loamy/dashboard'
      path: '/dashboard'
      fullPath: '/businesses/techworks/loamy/dashboard'
      preLoaderRoute: typeof BusinessesTechworksLoamyDashboardRouteImport
      parentRoute: typeof BusinessesTechworksLoamyRoute
    }
    '/businesses/techworks/loamy/auth': {
      id: '/businesses/techworks/loamy/auth'
      path: '/auth'
      fullPath: '/businesses/techworks/loamy/auth'
      preLoaderRoute: typeof BusinessesTechworksLoamyAuthRouteImport
      parentRoute: typeof BusinessesTechworksLoamyRoute
    }
  }
}

interface BusinessesTechworksLoamyRouteChildren {
  BusinessesTechworksLoamyAuthRoute: typeof BusinessesTechworksLoamyAuthRoute
  BusinessesTechworksLoamyDashboardRoute: typeof BusinessesTechworksLoamyDashboardRoute
}

const BusinessesTechworksLoamyRouteChildren: BusinessesTechworksLoamyRouteChildren =
  {
    BusinessesTechworksLoamyAuthRoute: BusinessesTechworksLoamyAuthRoute,
    BusinessesTechworksLoamyDashboardRoute:
      BusinessesTechworksLoamyDashboardRoute,
  }

const BusinessesTechworksLoamyRouteWithChildren =
  BusinessesTechworksLoamyRoute._addFileChildren(
    BusinessesTechworksLoamyRouteChildren,
  )

interface BusinessesTechworksRouteChildren {
  BusinessesTechworksLoamyRoute: typeof BusinessesTechworksLoamyRouteWithChildren
}

const BusinessesTechworksRouteChildren: BusinessesTechworksRouteChildren = {
  BusinessesTechworksLoamyRoute: BusinessesTechworksLoamyRouteWithChildren,
}

const BusinessesTechworksRouteWithChildren =
  BusinessesTechworksRoute._addFileChildren(BusinessesTechworksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoryRoute: StoryRoute,
  BusinessesEnergiesRoute: BusinessesEnergiesRoute,
  BusinessesEximRoute: BusinessesEximRoute,
  BusinessesStructuresRoute: BusinessesStructuresRoute,
  BusinessesTechworksRoute: BusinessesTechworksRouteWithChildren,
  BusinessesIndexRoute: BusinessesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
