/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StoryRouteImport } from './routes/story'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessesIndexRouteImport } from './routes/businesses.index'
import { Route as BusinessesTechworksRouteImport } from './routes/businesses.techworks'
import { Route as BusinessesStructuresRouteImport } from './routes/businesses.structures'
import { Route as BusinessesEximRouteImport } from './routes/businesses.exim'
import { Route as BusinessesEnergiesRouteImport } from './routes/businesses.energies'
import { Route as BusinessesTechworksIndexRouteImport } from './routes/businesses.techworks.index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesIndexRoute = BusinessesIndexRouteImport.update({
  id: '/businesses/',
  path: '/businesses/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesTechworksRoute = BusinessesTechworksRouteImport.update({
  id: '/businesses/techworks',
  path: '/businesses/techworks',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesStructuresRoute = BusinessesStructuresRouteImport.update({
  id: '/businesses/structures',
  path: '/businesses/structures',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesEximRoute = BusinessesEximRouteImport.update({
  id: '/businesses/exim',
  path: '/businesses/exim',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesEnergiesRoute = BusinessesEnergiesRouteImport.update({
  id: '/businesses/energies',
  path: '/businesses/energies',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesTechworksIndexRoute =
  BusinessesTechworksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BusinessesTechworksRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/terms': typeof TermsRoute
  '/businesses/energies': typeof BusinessesEnergiesRoute
  '/businesses/exim': typeof BusinessesEximRoute
  '/businesses/structures': typeof BusinessesStructuresRoute
  '/businesses/techworks': typeof BusinessesTechworksRouteWithChildren
  '/businesses/': typeof BusinessesIndexRoute
  '/businesses/techworks/': typeof BusinessesTechworksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/terms': typeof TermsRoute
  '/businesses/energies': typeof BusinessesEnergiesRoute
  '/businesses/exim': typeof BusinessesEximRoute
  '/businesses/structures': typeof BusinessesStructuresRoute
  '/businesses': typeof BusinessesIndexRoute
  '/businesses/techworks': typeof BusinessesTechworksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/terms': typeof TermsRoute
  '/businesses/energies': typeof BusinessesEnergiesRoute
  '/businesses/exim': typeof BusinessesEximRoute
  '/businesses/structures': typeof BusinessesStructuresRoute
  '/businesses/techworks': typeof BusinessesTechworksRouteWithChildren
  '/businesses/': typeof BusinessesIndexRoute
  '/businesses/techworks/': typeof BusinessesTechworksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/story'
    | '/terms'
    | '/businesses/energies'
    | '/businesses/exim'
    | '/businesses/structures'
    | '/businesses/techworks'
    | '/businesses/'
    | '/businesses/techworks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/story'
    | '/terms'
    | '/businesses/energies'
    | '/businesses/exim'
    | '/businesses/structures'
    | '/businesses'
    | '/businesses/techworks'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/story'
    | '/terms'
    | '/businesses/energies'
    | '/businesses/exim'
    | '/businesses/structures'
    | '/businesses/techworks'
    | '/businesses/'
    | '/businesses/techworks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoryRoute: typeof StoryRoute
  TermsRoute: typeof TermsRoute
  BusinessesEnergiesRoute: typeof BusinessesEnergiesRoute
  BusinessesEximRoute: typeof BusinessesEximRoute
  BusinessesStructuresRoute: typeof BusinessesStructuresRoute
  BusinessesTechworksRoute: typeof BusinessesTechworksRouteWithChildren
  BusinessesIndexRoute: typeof BusinessesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/': {
      id: '/businesses/'
      path: '/businesses'
      fullPath: '/businesses/'
      preLoaderRoute: typeof BusinessesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/techworks': {
      id: '/businesses/techworks'
      path: '/businesses/techworks'
      fullPath: '/businesses/techworks'
      preLoaderRoute: typeof BusinessesTechworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/structures': {
      id: '/businesses/structures'
      path: '/businesses/structures'
      fullPath: '/businesses/structures'
      preLoaderRoute: typeof BusinessesStructuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/exim': {
      id: '/businesses/exim'
      path: '/businesses/exim'
      fullPath: '/businesses/exim'
      preLoaderRoute: typeof BusinessesEximRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/energies': {
      id: '/businesses/energies'
      path: '/businesses/energies'
      fullPath: '/businesses/energies'
      preLoaderRoute: typeof BusinessesEnergiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/techworks/': {
      id: '/businesses/techworks/'
      path: '/'
      fullPath: '/businesses/techworks/'
      preLoaderRoute: typeof BusinessesTechworksIndexRouteImport
      parentRoute: typeof BusinessesTechworksRoute
    }
  }
}

interface BusinessesTechworksRouteChildren {
  BusinessesTechworksIndexRoute: typeof BusinessesTechworksIndexRoute
}

const BusinessesTechworksRouteChildren: BusinessesTechworksRouteChildren = {
  BusinessesTechworksIndexRoute: BusinessesTechworksIndexRoute,
}

const BusinessesTechworksRouteWithChildren =
  BusinessesTechworksRoute._addFileChildren(BusinessesTechworksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoryRoute: StoryRoute,
  TermsRoute: TermsRoute,
  BusinessesEnergiesRoute: BusinessesEnergiesRoute,
  BusinessesEximRoute: BusinessesEximRoute,
  BusinessesStructuresRoute: BusinessesStructuresRoute,
  BusinessesTechworksRoute: BusinessesTechworksRouteWithChildren,
  BusinessesIndexRoute: BusinessesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
